//! `mcp-audit init` — generate a default `.mcp-audit.toml` configuration.
//!
//! Auto-detects existing MCP configuration files (e.g. `claude_desktop_config.json`)
//! and generates a scanner configuration with all OWASP MCP Top 10 rules enabled.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::parser::McpConfig;
use crate::rules;

// ── Configuration model ─────────────────────────────────────────────────

/// Root scanner configuration, deserialized from `.mcp-audit.toml`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ScannerConfig {
    pub scanner: ScannerSection,
    pub rules: RulesSection,
    pub ignore: IgnoreSection,
    pub ci: CiSection,
}

/// `[scanner]` — core scanning settings.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ScannerSection {
    /// Paths to MCP configuration files. Empty = auto-detect.
    pub sources: Vec<String>,
    /// Minimum severity to report: critical, high, medium, low, info.
    pub severity_threshold: String,
    /// Default output format: json, table, markdown, sarif.
    pub output_format: String,
}

/// `[rules]` — rule enable/disable lists.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RulesSection {
    /// Enabled rule IDs (all by default).
    pub enabled: Vec<String>,
    /// Disabled rule IDs (takes precedence over enabled).
    pub disabled: Vec<String>,
}

/// `[ignore]` — patterns to exclude from scanning.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct IgnoreSection {
    /// Server names to skip entirely.
    pub servers: Vec<String>,
    /// Individual findings to suppress, e.g. `"MCP-04:my-local-server"`.
    pub findings: Vec<String>,
}

/// `[ci]` — CI/CD-specific overrides.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CiSection {
    /// Fail the pipeline if any finding meets or exceeds this severity.
    pub fail_severity: String,
    /// Path to write the CI report file (empty = stdout only).
    pub report_file: String,
    /// Report format for CI output.
    pub report_format: String,
}

// ── Defaults ────────────────────────────────────────────────────────────

impl ScannerConfig {
    /// Build a default configuration, optionally tuned for CI.
    pub fn generate(ci_mode: bool) -> Self {
        let detected = detect_mcp_sources();
        let rule_ids = all_rule_ids();

        if ci_mode {
            Self::ci_defaults(detected, rule_ids)
        } else {
            Self::interactive_defaults(detected, rule_ids)
        }
    }

    /// Default configuration for local/interactive use.
    fn interactive_defaults(sources: Vec<String>, rule_ids: Vec<String>) -> Self {
        Self {
            scanner: ScannerSection {
                sources,
                severity_threshold: "low".into(),
                output_format: "table".into(),
            },
            rules: RulesSection {
                enabled: rule_ids,
                disabled: vec![],
            },
            ignore: IgnoreSection {
                servers: vec![],
                findings: vec![],
            },
            ci: CiSection {
                fail_severity: "high".into(),
                report_file: String::new(),
                report_format: "sarif".into(),
            },
        }
    }

    /// Configuration optimised for CI/CD pipelines.
    fn ci_defaults(sources: Vec<String>, rule_ids: Vec<String>) -> Self {
        Self {
            scanner: ScannerSection {
                sources,
                severity_threshold: "medium".into(),
                output_format: "sarif".into(),
            },
            rules: RulesSection {
                enabled: rule_ids,
                disabled: vec![],
            },
            ignore: IgnoreSection {
                servers: vec![],
                findings: vec![],
            },
            ci: CiSection {
                fail_severity: "high".into(),
                report_file: "mcp-audit-results.sarif".into(),
                report_format: "sarif".into(),
            },
        }
    }

    /// Render the configuration as a well-commented TOML string.
    pub fn render_toml(&self) -> String {
        let mut out = String::with_capacity(2048);

        // Header
        out.push_str("# MCP Audit Configuration\n");
        out.push_str("# Generated by `mcp-audit init`\n");
        out.push_str("# Documentation: https://github.com/Norbi0801/mcp-audit\n");
        out.push('\n');

        // [scanner]
        out.push_str("[scanner]\n");
        out.push_str("# Path(s) to MCP configuration files to scan.\n");
        out.push_str("# Leave empty to auto-detect from common locations:\n");
        out.push_str("#   claude_desktop_config.json, .mcp.json, mcp.json, .mcp/*.json\n");
        out.push_str(&format!(
            "sources = {}\n",
            format_string_array(&self.scanner.sources)
        ));
        out.push('\n');
        out.push_str("# Minimum severity threshold for reporting findings.\n");
        out.push_str("# Options: critical, high, medium, low, info\n");
        out.push_str(&format!(
            "severity_threshold = {:?}\n",
            self.scanner.severity_threshold
        ));
        out.push('\n');
        out.push_str("# Default output format.\n");
        out.push_str("# Options: json, table, markdown, sarif\n");
        out.push_str(&format!(
            "output_format = {:?}\n",
            self.scanner.output_format
        ));
        out.push('\n');

        // [rules]
        out.push_str("[rules]\n");
        out.push_str("# Enabled security rules (OWASP MCP Top 10).\n");
        out.push_str("# All rules are enabled by default.\n");
        out.push_str(&render_rules_array("enabled", &self.rules.enabled));
        out.push('\n');
        out.push_str("# Disable specific rules (takes precedence over enabled).\n");
        out.push_str(&format!(
            "disabled = {}\n",
            format_string_array(&self.rules.disabled)
        ));
        out.push('\n');

        // [ignore]
        out.push_str("[ignore]\n");
        out.push_str("# Server names to exclude from scanning.\n");
        out.push_str(&format!(
            "servers = {}\n",
            format_string_array(&self.ignore.servers)
        ));
        out.push('\n');
        out.push_str("# Suppress individual findings by \"RULE_ID:server_name\".\n");
        out.push_str("# Example: [\"MCP-04:my-local-dev-server\"]\n");
        out.push_str(&format!(
            "findings = {}\n",
            format_string_array(&self.ignore.findings)
        ));
        out.push('\n');

        // [ci]
        out.push_str("[ci]\n");
        out.push_str("# Fail the CI pipeline if any finding meets or exceeds this severity.\n");
        out.push_str(&format!("fail_severity = {:?}\n", self.ci.fail_severity));
        out.push('\n');
        out.push_str("# Write report to a file (leave empty for stdout only).\n");
        out.push_str(&format!("report_file = {:?}\n", self.ci.report_file));
        out.push('\n');
        out.push_str("# Report format for CI output.\n");
        out.push_str("# Options: json, sarif\n");
        out.push_str(&format!("report_format = {:?}\n", self.ci.report_format));

        out
    }

    /// Parse a `.mcp-audit.toml` file back into a [`ScannerConfig`].
    pub fn from_file(path: &Path) -> Result<Self, InitError> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| InitError::Io(path.display().to_string(), e))?;
        toml::from_str(&content).map_err(|e| InitError::TomlParse(path.display().to_string(), e))
    }
}

// ── Auto-detection ──────────────────────────────────────────────────────

/// Discover MCP configuration files and return their paths as strings.
///
/// Uses the same search logic as `mcp-audit scan` (see [`McpConfig::find_config_files`]).
pub fn detect_mcp_sources() -> Vec<String> {
    McpConfig::find_config_files()
        .into_iter()
        .map(|p| normalize_path(&p))
        .collect()
}

/// Turn an absolute path into a relative one when it lives under the CWD,
/// otherwise return the full path. This keeps `.mcp-audit.toml` portable.
fn normalize_path(path: &Path) -> String {
    if let Ok(cwd) = std::env::current_dir() {
        if let Ok(rel) = path.strip_prefix(&cwd) {
            return rel.display().to_string();
        }
    }
    path.display().to_string()
}

// ── Write to disk ───────────────────────────────────────────────────────

/// Write the configuration to the given path.
///
/// Returns an error if the file already exists and `force` is false.
pub fn write_config(
    config: &ScannerConfig,
    path: &Path,
    force: bool,
) -> Result<PathBuf, InitError> {
    if path.exists() && !force {
        return Err(InitError::AlreadyExists(path.display().to_string()));
    }

    // Create parent directories if needed.
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)
                .map_err(|e| InitError::Io(parent.display().to_string(), e))?;
        }
    }

    let content = config.render_toml();
    std::fs::write(path, &content).map_err(|e| InitError::Io(path.display().to_string(), e))?;

    Ok(path.to_path_buf())
}

// ── Errors ──────────────────────────────────────────────────────────────

/// Errors specific to the `init` subcommand.
#[derive(Debug, thiserror::Error)]
pub enum InitError {
    #[error("file already exists: {0} (use --force to overwrite)")]
    AlreadyExists(String),

    #[error("I/O error on {0}: {1}")]
    Io(String, #[source] std::io::Error),

    #[error("failed to parse TOML in {0}: {1}")]
    TomlParse(String, #[source] toml::de::Error),
}

// ── Helpers ─────────────────────────────────────────────────────────────

/// Collect all rule IDs from the rule engine.
fn all_rule_ids() -> Vec<String> {
    rules::list_rules().into_iter().map(|r| r.id).collect()
}

/// Format a `Vec<String>` as a TOML inline array.
fn format_string_array(items: &[String]) -> String {
    if items.is_empty() {
        return "[]".into();
    }

    // Short arrays inline, long arrays multi-line.
    let total_len: usize = items.iter().map(|s| s.len() + 4).sum::<usize>() + 2;
    if total_len <= 80 {
        let inner: Vec<String> = items.iter().map(|s| format!("{s:?}")).collect();
        format!("[{}]", inner.join(", "))
    } else {
        let mut out = String::from("[\n");
        for item in items {
            out.push_str(&format!("    {item:?},\n"));
        }
        out.push(']');
        out
    }
}

/// Render the enabled rules array with rule-name comments.
fn render_rules_array(key: &str, ids: &[String]) -> String {
    if ids.is_empty() {
        return format!("{key} = []\n");
    }

    let rule_infos = rules::list_rules();

    let mut out = format!("{key} = [\n");
    for id in ids {
        let comment = rule_infos
            .iter()
            .find(|r| r.id == *id)
            .map(|r| format!("  # {}", r.name))
            .unwrap_or_default();
        out.push_str(&format!("    {id:?},{comment}\n"));
    }
    out.push_str("]\n");
    out
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_interactive_config_has_all_rules() {
        let config = ScannerConfig::generate(false);
        assert_eq!(config.rules.enabled.len(), 19);
        assert!(config.rules.disabled.is_empty());
        assert_eq!(config.scanner.severity_threshold, "low");
        assert_eq!(config.scanner.output_format, "table");
    }

    #[test]
    fn generate_ci_config_has_strict_defaults() {
        let config = ScannerConfig::generate(true);
        assert_eq!(config.scanner.severity_threshold, "medium");
        assert_eq!(config.scanner.output_format, "sarif");
        assert_eq!(config.ci.fail_severity, "high");
        assert_eq!(config.ci.report_file, "mcp-audit-results.sarif");
        assert_eq!(config.ci.report_format, "sarif");
    }

    #[test]
    fn render_toml_is_parseable() {
        let config = ScannerConfig::generate(false);
        let toml_str = config.render_toml();

        // Must be valid TOML.
        let parsed: ScannerConfig =
            toml::from_str(&toml_str).expect("rendered TOML must be parseable");

        // Round-trip must preserve values.
        assert_eq!(
            parsed.scanner.severity_threshold,
            config.scanner.severity_threshold
        );
        assert_eq!(parsed.scanner.output_format, config.scanner.output_format);
        assert_eq!(parsed.rules.enabled, config.rules.enabled);
        assert_eq!(parsed.rules.disabled, config.rules.disabled);
        assert_eq!(parsed.ignore.servers, config.ignore.servers);
        assert_eq!(parsed.ignore.findings, config.ignore.findings);
        assert_eq!(parsed.ci.fail_severity, config.ci.fail_severity);
        assert_eq!(parsed.ci.report_file, config.ci.report_file);
        assert_eq!(parsed.ci.report_format, config.ci.report_format);
    }

    #[test]
    fn render_toml_ci_is_parseable() {
        let config = ScannerConfig::generate(true);
        let toml_str = config.render_toml();

        let parsed: ScannerConfig =
            toml::from_str(&toml_str).expect("rendered CI TOML must be parseable");

        assert_eq!(parsed, config);
    }

    #[test]
    fn render_toml_contains_comments() {
        let config = ScannerConfig::generate(false);
        let toml_str = config.render_toml();

        assert!(toml_str.contains("# MCP Audit Configuration"));
        assert!(toml_str.contains("# Generated by `mcp-audit init`"));
        assert!(toml_str.contains("[scanner]"));
        assert!(toml_str.contains("[rules]"));
        assert!(toml_str.contains("[ignore]"));
        assert!(toml_str.contains("[ci]"));
        assert!(toml_str.contains("OWASP MCP Top 10"));
    }

    #[test]
    fn render_toml_contains_rule_name_comments() {
        let config = ScannerConfig::generate(false);
        let toml_str = config.render_toml();

        // Each enabled rule should have a comment with the rule name.
        assert!(toml_str.contains("# Tool Poisoning"));
        assert!(toml_str.contains("# Excessive Permissions"));
    }

    #[test]
    fn write_config_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".mcp-audit.toml");

        let config = ScannerConfig::generate(false);
        let result = write_config(&config, &path, false);

        assert!(result.is_ok());
        assert!(path.exists());

        // Verify it's valid TOML.
        let content = std::fs::read_to_string(&path).unwrap();
        let parsed: ScannerConfig = toml::from_str(&content).unwrap();
        assert_eq!(parsed.rules.enabled.len(), 19);
    }

    #[test]
    fn write_config_refuses_overwrite_without_force() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".mcp-audit.toml");

        // Create the file first.
        std::fs::write(&path, "existing content").unwrap();

        let config = ScannerConfig::generate(false);
        let result = write_config(&config, &path, false);

        assert!(result.is_err());
        let err = result.unwrap_err();
        assert!(err.to_string().contains("already exists"));

        // Original content should be preserved.
        let content = std::fs::read_to_string(&path).unwrap();
        assert_eq!(content, "existing content");
    }

    #[test]
    fn write_config_force_overwrites() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".mcp-audit.toml");

        // Create the file first.
        std::fs::write(&path, "old content").unwrap();

        let config = ScannerConfig::generate(true);
        let result = write_config(&config, &path, true);

        assert!(result.is_ok());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("[scanner]"));
        assert!(content.contains("sarif")); // CI mode
    }

    #[test]
    fn write_config_creates_parent_directories() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir
            .path()
            .join("nested")
            .join("deep")
            .join(".mcp-audit.toml");

        let config = ScannerConfig::generate(false);
        let result = write_config(&config, &path, false);

        assert!(result.is_ok());
        assert!(path.exists());
    }

    #[test]
    fn from_file_parses_valid_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.toml");

        let original = ScannerConfig::generate(false);
        std::fs::write(&path, original.render_toml()).unwrap();

        let loaded = ScannerConfig::from_file(&path).unwrap();
        assert_eq!(loaded, original);
    }

    #[test]
    fn from_file_returns_error_for_missing_file() {
        let result = ScannerConfig::from_file(Path::new("/nonexistent/.mcp-audit.toml"));
        assert!(result.is_err());
    }

    #[test]
    fn from_file_returns_error_for_invalid_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.toml");
        std::fs::write(&path, "this is not valid toml [[[").unwrap();

        let result = ScannerConfig::from_file(&path);
        assert!(result.is_err());
    }

    #[test]
    fn format_string_array_empty() {
        assert_eq!(format_string_array(&[]), "[]");
    }

    #[test]
    fn format_string_array_short() {
        let items = vec!["a".into(), "b".into()];
        let result = format_string_array(&items);
        assert_eq!(result, r#"["a", "b"]"#);
    }

    #[test]
    fn format_string_array_long_goes_multiline() {
        let items: Vec<String> = (0..20).map(|i| format!("long-item-name-{i}")).collect();
        let result = format_string_array(&items);
        assert!(result.starts_with("[\n"));
        assert!(result.ends_with(']'));
        assert!(result.contains("    \"long-item-name-0\",\n"));
    }

    #[test]
    fn normalize_path_returns_relative_under_cwd() {
        let cwd = std::env::current_dir().unwrap();
        let abs = cwd.join("some_file.json");
        let result = normalize_path(&abs);
        assert_eq!(result, "some_file.json");
    }

    #[test]
    fn normalize_path_returns_absolute_outside_cwd() {
        let path = PathBuf::from("/tmp/totally/different/config.json");
        let result = normalize_path(&path);
        assert_eq!(result, "/tmp/totally/different/config.json");
    }

    #[test]
    fn all_rule_ids_returns_all() {
        let ids = all_rule_ids();
        assert_eq!(ids.len(), 19);
        assert!(ids[0].starts_with("MCP-"));
    }
}
